TITLE="Programming - Computer - Rick's Favourite Links"

.PHONY: all

index.html: ../../index.py index.csv
	python ../../index.py index.csv index.html $(TITLE)

all:
	python ../../index.py index.csv index.html $(TITLE)
	make -C assembly all
	make -C awk all
	make -C bash all
	make -C basic all
	make -C c all
	make -C challenges all
	make -C cpp all
	make -C database all
	make -C general all
	make -C java all
	make -C javascript all
	make -C mobile all
	make -C php all
	make -C python all
	make -C regex all
	make -C web all
